CREATE TABLE MEMBER
( 
    ID VARCHAR2(50),
    PWD VARCHAR2(50),
    NAME VARCHAR2(50),
    GENDER VARCHAR2(50),
    AGE NUMBER,
    BIRTHDAY VARCHAR2(50),
    PHONE VARCHAR2(50),
    REGDATE DATE
    ); 

SELECT *
FROM member;

CREATE TABLE MEMBER_ROLE
(
MEMBER_ID NVARCHAR2(50),
ROLE_ID VARCHAR2(50)
);

INSERT INTO MEMBER(ID,PWD) VALUES('newlec','111');
INSERT INTO MEMBER(ID,PWD) VALUES('dragon','111');

UPDATE MEMBER SET pwd='222'
WHERE ID='dragon';

SELECT *
FROM member;

SELECT ROWNUM,a.*
FROM
(SELECT empno,ename
FROM emp
ORDER BY sal)a;

SELECT ROWNUM rn,empno,ename
FROM emp
WHERE ROWNUM <= 10; 

SELECT *
FROM
(SELECT ROWNUM rn,empno,ename
FROM emp)
WHERE rn >= 11 and rn <= 14;



